### ISSUE TITLE
FsHttp

### ISSUE THREAD

**Issue by ronaldschlenker** [fsprojects/fsprojects-admin#33]
Related: https://github.com/ronaldschlenker/FsHttp/pull/79

Although there are still some TODOs open before transferring and releasing the next major, I would be happy to transfer FsHttp to fsprojects.

Thank you for maintaining this space.

**Comment by dsyme** [comment]
@ronaldschlenker Welcome!  I've sent you an org invite. After you have it you should be able to transfer the project in

**Comment by ronaldschlenker** [comment]
Thank you very much, @dsyme. I was able to sucessfully join the @fsprojects organization. The invitation for the [fsprojects-admin repo](https://github.com/fsprojects/fsprojects-admin/invitations) resulted in this error message:

> Sorry, we couldn't find that repository invitation. It is possible that the invitation was revoked or that you are not logged into the invited account.

Was the invitation to the fsprojects-admin repo intentional, or just a mistake? Since I'm a member of fsprojects now, I should proceed with

* creating a `fsprojects/FsHttp` repo
* transfer the 'ronaldschlenker/FsHttp' repo in

Is that correct?

**Comment by sergey-tihon** [comment]
@ronaldschlenker there is no need to create new repo, just go to project setting and find `Transfer` button there - https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-user-account

**Comment by ronaldschlenker** [comment]
Done :) Thanks!

**Comment by ronaldschlenker** [comment]
@sergey-tihon Travis-CI was used for build and tests. It seems that got broken since I can only select the repos under my GitHub account. Do you know how CI is managed usually for fsprojects?

**Comment by dsyme** [comment]
We're normally using GitHub Actions but can enable Travis if you need it

**Comment by dsyme** [comment]
> We're normally using GitHub Actions but can enable Travis if you need it

We can enable Travis for FsHttp after you move it into the org, thanks

**Comment by ronaldschlenker** [comment]
Thanks, I try out GitHub Actions.

**Comment by ronaldschlenker** [comment]
@sergey-tihon could it be possible to access the settings page of the repo?

**Comment by sergey-tihon** [comment]
@ronaldschlenker definitely yes. By default Github convert you role to `Write`. After migration we manually restore it back to `Admin` for owners. Please check.

**Comment by ronaldschlenker** [comment]
It’s there! 😊 Thanks for your support. So I guess I start the search for a backup admin and improve the docs.

Did you receive the Nuget invitation? (I’ve sent it right now)

**Comment by sergey-tihon** [comment]
> Did you receive the Nuget invitation? (I’ve sent it right now)

yes, accepted. thank you

**Comment by sergey-tihon** [comment]
I also see an invitation to install Travis CI.
@ronaldschlenker  do you still need it or you are ok with Github Actions?

**Comment by ronaldschlenker** [comment]
> do you still need it or you are ok with Github Actions?

No @sergey-tihon  - I don’t need it anymore, thus I switched to GitHub Actions yesterday. Please excuse the irritation.
