### ISSUE TITLE
FsLocalState

### ISSUE THREAD

**Issue by ronaldschlenker** [fsprojects/fsprojects-admin#37]
Hello,

I currently work on a library which I call "FsLocalState". The repo is [here](https://github.com/ronaldschlenker/FsLocalState), and there is a description and some samples in the README. 

Basically, it's about composing 'state-aware' functions as if they were just normal functions. Initially, I did that for signal processing and physics simulation, where is always a lot of state involved, with non-linear computations, e.g. when designing filters or modeling and numerically solving differential equations. But it's quite generic, and I guess it could be useful for other applications - not only in the "working with data series" domain. Another brief idea I had was creating a view engine and investigate how this relates to other approaches like react / virtual dom or Svelte/Sutil-like things. Maybe some other people are interested in this, too, and come up with other use cases - who knows...

If you think that this library would fit in fsprojects, then I could move it here?

Thanks, and have a nice sunday!

**Comment by dsyme** [comment]
Yes, it's a good fit, feel free to move it in. 

I'd like to recommend/request a name change as part of moving in - "FsXyz" is generally used for tooling, eg "FsCheck".  Yet, the library is too experimental for "FSharp.Data.XYZ" 

So I'd encourage a new name. Maybe just under some nanespaces, eg "Utilities.LocalState" or "Schlenker.LocalState"?? 

@sergey_tihon As an aside I guess we should adjust the policies to mention a bit about naming, eg 

1. We may make recommendations about naming
2. "FsXyz" is for tooling
3. "FSharp.Abc.Xyz" is for maturing canonical libraries and should only be used with agreement
4. Give some examples

**Comment by ronaldschlenker** [comment]
@sergey-tihon @dsyme I moved it in.

For the naming: Is it required to prefix the name at all? If not, I would propably just use `Locsta` as namespace for now.

**Comment by dsyme** [comment]
@ronaldschlenker No, it's not required, Locsta seems like a fine name.

**Comment by sergey-tihon** [comment]
@ronaldschlenker just restored you Admin access to the repo

**Comment by ronaldschlenker** [comment]
Thanks!
