### ISSUE TITLE
Merge, or replace fsprojects/fsharp-languge-server with faldor20/fsharp-language-server 

### ISSUE THREAD

**Issue by faldor20** [fsprojects/fsprojects-admin#40]
The original [fsprojects/fsharp-language-server](https://github.com/fsprojects/fsharp-language-server) repo seems completely unmaintained. I have forked it and republished the extension with a large number of improvements (probably a few extra bugs too :b ), from myself and other members of the community.

As requested in this issue https://github.com/faldor20/fsharp-language-server/discussions/15 , would it be possible to merge the two projects, or replace the old one, or some such, so that members of the community have less confusion and duplication?

Thanks.

**Comment by sergey-tihon** [comment]
@georgewfraser what do you think? would you mind to add @faldor20 as co-maintainer of [fsprojects/fsharp-language-server](https://github.com/fsprojects/fsharp-language-server)?

@fsprojects/tooling-team , @dsyme  appreciate your thoughts as well.

**Comment by dsyme** [comment]
This seems reasonable

**Comment by cartermp** [comment]
agreed

**Comment by dsyme** [comment]
@faldor20 I have sent a maintainer invitation to you.  You will now be able to make a pull request and self-merge it and continue development together with other contributors 

@georgewfraser Please let us know if you have any concerns.

**Comment by faldor20** [comment]
@dsyme Thankyou very much.
